INFO;2020-10-24 20:12:10;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:12:10;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:12:10;fs_functions.py;fs_functions;196;A última modificação do arquivo fs_functions.py (202010) não bate com o validador (202009)
INFO;2020-10-24 20:12:10;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:12:10;fs_functions.py;fs_functions;238;Cópia realizada com sucesso. Origem: C:/Users/thipa/Desktop/workspaces/python-components/file_system/fs_functions.py - Destino: C:/Users/thipa/Desktop/workspaces/python-components/testes/copia_fs_functions.py
INFO;2020-10-24 20:12:27;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:12:27;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:12:27;fs_functions.py;fs_functions;196;A última modificação do arquivo fs_functions.py (202010) não bate com o validador (202009)
INFO;2020-10-24 20:12:27;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
ERROR;2020-10-24 20:12:27;fs_functions.py;fs_functions;240;Falha durante a cópia. Exception lançada: [Errno 2] No such file or directory: 'C:/Users/thipa/Desktop/workspaces/python-components/testes/fake_folder/copia_fs_functions.py'
INFO;2020-10-24 20:13:08;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:13:08;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:13:08;fs_functions.py;fs_functions;196;A última modificação do arquivo fs_functions.py (202010) não bate com o validador (202009)
INFO;2020-10-24 20:13:08;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:17:49;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:17:49;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:17:49;fs_functions.py;fs_functions;196;A última modificação do arquivo fs_functions.py (202010) não bate com o validador (202009)
INFO;2020-10-24 20:17:49;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:17:49;fs_functions.py;fs_functions;241;Falha ao copiar arquivo para o destino por inexistência do diretório. Exception lançada: [Errno 2] No such file or directory: 'C:/Users/thipa/Desktop/workspaces/python-components/testes/fake_folder/copia_fs_functions.py'
DEBUG;2020-10-24 20:17:49;fs_functions.py;fs_functions;242;Criando novo diretório
INFO;2020-10-24 20:17:49;fs_functions.py;fs_functions;249;Cópia realizada com sucesso. Origem: C:/Users/thipa/Desktop/workspaces/python-components/file_system/fs_functions.py - Destino: C:/Users/thipa/Desktop/workspaces/python-components/testes/fake_folder/copia_fs_functions.py
INFO;2020-10-24 20:23:53;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:23:53;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:23:53;fs_functions.py;fs_functions;196;A última modificação do arquivo fs_functions.py (202010) não bate com o validador (202009)
INFO;2020-10-24 20:23:53;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:23:53;fs_functions.py;fs_functions;241;Falha ao copiar arquivo para o destino por inexistência do diretório. Exception lançada: [Errno 2] No such file or directory: 'C:/Users/thipa/Desktop/workspaces/python-components/testes/fake_folder/fake_folder2/fake_folder3/fake_folder4/copia_fs_functions.py'
DEBUG;2020-10-24 20:23:53;fs_functions.py;fs_functions;242;Criando novo diretório
INFO;2020-10-24 20:25:07;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:25:07;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:25:07;fs_functions.py;fs_functions;196;A última modificação do arquivo fs_functions.py (202010) não bate com o validador (202009)
INFO;2020-10-24 20:25:07;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:25:07;fs_functions.py;fs_functions;241;Falha ao copiar arquivo para o destino por inexistência do diretório. Exception lançada: [Errno 2] No such file or directory: 'C:/Users/thipa/Desktop/workspaces/python-components/testes/fake_folder/fake_folder2/fake_folder3/fake_folder4/copia_fs_functions.py'
DEBUG;2020-10-24 20:25:07;fs_functions.py;fs_functions;242;Criando novo diretório
INFO;2020-10-24 20:25:22;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:25:22;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:25:22;fs_functions.py;fs_functions;196;A última modificação do arquivo fs_functions.py (202010) não bate com o validador (202009)
INFO;2020-10-24 20:25:22;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:25:22;fs_functions.py;fs_functions;241;Falha ao copiar arquivo para o destino por inexistência do diretório. Exception lançada: [Errno 2] No such file or directory: 'C:/Users/thipa/Desktop/workspaces/python-components/testes/fake_folder/fake_folder2/fake_folder3/fake_folder4/copia_fs_functions.py'
DEBUG;2020-10-24 20:25:22;fs_functions.py;fs_functions;242;Criando novo diretório
INFO;2020-10-24 20:25:22;fs_functions.py;fs_functions;249;Cópia realizada com sucesso. Origem: C:/Users/thipa/Desktop/workspaces/python-components/file_system/fs_functions.py - Destino: C:/Users/thipa/Desktop/workspaces/python-components/testes/fake_folder/fake_folder2/fake_folder3/fake_folder4/copia_fs_functions.py
INFO;2020-10-24 20:27:14;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
INFO;2020-10-24 20:27:14;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:27:14;fs_functions.py;fs_functions;196;A última modificação do arquivo fs_functions.py (202010) não bate com o validador (202009)
INFO;2020-10-24 20:27:14;fs_functions.py;fs_functions;121;Arquivo fs_functions.py presente na origem C:/Users/thipa/Desktop/workspaces/python-components/file_system
WARNING;2020-10-24 20:27:14;fs_functions.py;fs_functions;241;Falha ao copiar arquivo para o destino por inexistência do diretório. Exception lançada: [Errno 2] No such file or directory: 'C:/Users/thipa/Desktop/workspaces/python-components/testes/fake_folder2/copia_fs_functions.py'
DEBUG;2020-10-24 20:27:14;fs_functions.py;fs_functions;242;Criando novo diretório
INFO;2020-10-24 20:27:14;fs_functions.py;fs_functions;249;Cópia realizada com sucesso. Origem: C:/Users/thipa/Desktop/workspaces/python-components/file_system/fs_functions.py - Destino: C:/Users/thipa/Desktop/workspaces/python-components/testes/fake_folder2/copia_fs_functions.py
